[theme]
base = "light"
primaryColor = "#087f83"
backgroundColor = "#f5f7fa"
secondaryBackgroundColor = "#eaf0f5"
textColor = "#16283e"
font = "sans serif"
[server]
address = "127.0.0.1"
maxUploadSize = 100
[browser]
gatherUsageStats = false
